name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK (SDK 31, Build Tools 31.0.0)
        run: |
          yes | sudo apt-get update
          yes | sudo apt-get install -y zip unzip python3-pip openjdk-17-jdk
          yes | sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk "platform-tools" "build-tools;31.0.0" "platforms;android-31"

      - name: Install Buildozer and Compile
        run: |
          pip3 install --user buildozer cython
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DataMonitor-APK
          path: bin/*.apk
