name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          cd $HOME/android-sdk/cmdline-tools/latest
          curl -O https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          rm commandlinetools-linux-8512546_latest.zip
          mv cmdline-tools/* ./
          rm -rf cmdline-tools

      - name: Set up ANDROID_HOME and PATH
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Install Android SDK Packages
        run: |
          chmod +x $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-30" \
            "build-tools;33.0.2"

      - name: Install Buildozer and Compile APK
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --user buildozer cython
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DataMonitor-APK
          path: bin/*.apk

