name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: '13.0'

      - name: Install Android Build-Tools and accept licenses
        run: |
          # Instalar herramientas necesarias
          sudo apt-get update
          sudo apt-get install -y zip unzip python3-pip
          pip3 install --user buildozer cython

          # Instalar Build-Tools y NDK específicos
          sdkmanager "build-tools;33.0.2" "ndk;23.1.7779620" "platforms;android-31"
          yes | sdkmanager --licenses

      - name: Build APK with Buildozer
        run: |
          # Inicializar buildozer.spec si no existe
          buildozer init || true
          # Compilar la APK
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DataMonitor-APK
          path: ./bin/*.apk
