name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies and Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip python3-pip curl libncurses5-dev
          pip3 install --user --upgrade buildozer cython

      - name: Install Android SDK manually
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -O https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d tools
          rm commandlinetools-linux-8512546_latest.zip
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/tools/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept Licenses and Install SDK Packages
        run: |
          export PATH=$HOME/android-sdk/cmdline-tools/tools/bin:$PATH
          yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses
          sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-30" \
            "build-tools;33.0.2"

      - name: Build APK
        run: |
          export PATH=$HOME/.local/bin:$PATH
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: datamonitor-apk
          path: bin/*.apk
