name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        run: |
          # Descargar e instalar las herramientas de línea de comandos del Android SDK
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/cmdline-tools.zip
          unzip /tmp/cmdline-tools.zip -d /tmp
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv /tmp/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          # Instalar Build-Tools, NDK y plataformas
          yes | sdkmanager "build-tools;33.0.2" "ndk;23.1.7779620" "platforms;android-31"
          yes | sdkmanager --licenses

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip python3-pip
          pip3 install --user buildozer cython

      - name: Build APK with Buildozer
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          # Inicializar buildozer.spec si no existe
          buildozer init || true
          # Compilar la APK
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DataMonitor-APK
          path: ./bin/*.apk
