name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Usamos Python 3.9 para compatibilidad con Buildozer

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip curl libncurses5-dev

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-tools-version: '10406996_latest'

      - name: Aceptar licencias del Android SDK
        run: yes | sdkmanager --licenses

      - name: Instalar paquetes del Android SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;33.0.2" "build-tools;36.0.0"

      - name: Verificar AIDL
        run: find $ANDROID_HOME/build-tools -name aidl

      - name: Instalar Buildozer y dependencias
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Compilar APK con Buildozer
        run: buildozer android debug

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: datamonitor-apk
          path: bin/*.apk

