name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719  # Usa versión 16.0

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses

      - name: Install Build-Tools
        run: |
          sdkmanager "build-tools;33.0.2"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip python3-pip
          pip3 install --user buildozer cython

      - name: Build APK with Buildozer
        run: |
          buildozer init || true
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DataMonitor-APK
          path: ./bin/*.apk
